# Configuration for Yasb (Yet Another Status Bar)

watch_stylesheet: true
watch_config: true

bars:
  status-bar:
    enabled: true
    screens: ['1']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: true
      acrylic: true 
      dark: false 
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40 
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      # left:   ["komorebi_workspaces", "komorebi_active_layout"]
      # center: ["active_window"]
      # right:  ["cpu", "memory", "wifi", "battery", "clock"]
      left:   ["start_button", "komorebi_workspaces", "komorebi_active_layout", "active_window"]
      center: ["clock"]
      right:  ["cpu", "memory", "wifi", "battery", "notification"]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: "No Active Window"
      max_length: 48
      max_length_ellipsis: ".."
      monitor_exclusive: false

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon}  {percent}%"
      label_alt: "{icon}  {percent}% | time: {time_remaining}"
      time_remaining_natural: false

  clock:
    type: "yasb.clock.ClockWidget"
    options:
        label: "\uf455  {%a %d %b %I:%M %p}"
        label_alt: "\uf455  {%A %d %B %Y %I:%M %p}"
        timezones: ["Asia/Kolkata"]
        callbacks:
          on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
          on_right: "next_timezone"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\udb80\udf5b {info[percent][total]}%"
      label_alt: "\udb80\udf5b {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
          on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
        label: "\uf200  {virtual_mem_percent}%"
        label_alt: "\uf200  {virtual_mem_free}"
        update_interval: 2000
        callbacks:
          on_right: "exec cmd /c Taskmgr"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
        label: "{wifi_icon}"
        label_alt: "{wifi_icon}  {wifi_name}"
        update_interval: 5000
        wifi_icons:
          - "\udb82\udd2e"  # 0% strength (no wifi)
          - "\udb82\udd1f"  # 1-25% strength
          - "\udb82\udd22"  # 26-50% strength
          - "\udb82\udd25"  # 51-75% strength
          - "\udb82\udd28"  # 76-100% strength. Alternate theming: \uf1eb
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
        label: "\ueb01 \ueab4 {download_speed} | \ueab7 {upload_speed}"
        label_alt: "\ueb01 \ueab4 {upload_speed} | \ueab7 {download_speed}"
        update_interval: 1000 # Update interval should be a multiple of 1000
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "{name}" # default: {name}
        label_default_name: "{index}" # default: {index}
        label_zero_index: false
        hide_empty_workspaces: false

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: false
      label: "{icon}"
      layout_icons:
        bsp: "[\\\\]"
        columns: "[||]"
        rows: "[==]"
        vertical_stack: "[V]="
        horizontal_stack: "[H]="
        ultrawide_vertical_stack: "||="
        monocle: "[M]"
        maximised: "[X]"
        floating: "><>"
        paused: "[P]"
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'

  # Some custom widgets

  explorer_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf07c"
      label_alt: "Explorer"
      class_name: "explorer-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec explorer.exe"
        on_right: "toggle_label"

  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf3c5 {data[city]}, {data[region]}"
      label_alt: "\uf3c5 {data[ip]} [{data[country]}]"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000                                        # every 5 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl"                           # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  weather:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf0c2  {data[current_condition][0][temp_C]}\u00b0c"
      label_alt: "\uf0c2  {data[current_condition][0][weatherDesc][0][value]}"
      class_name: "weather-widget"
      exec_options:
        run_cmd: "curl.exe  wttr.in/Nashik?format=j1"
        # run every hour
        run_interval: 3600000
        return_format: "json"
  lang:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\udb80\udf0c {data}"
      label_alt: "\udb81\udfd3 {data}"
      class_name: "lang-widget"
      exec_options:
        run_cmd: "powershell add-type -assemblyname system.windows.forms;([system.windows.forms.inputlanguage]::currentinputlanguage).Culture.Name"
        # run every 3 sec
        run_interval: 3000
        return_format: "string"

  notification:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf0f3"
      label_alt: "\uf49a"
      class_name: "notification-widget"
      callbacks:
        on_left: "exec autohotkey64 C:/Users/Ashwin/.dotfiles/yasb/functions/notification-widget.ahk"
        on_right: "toggle_label"

  start_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a Start"
      class_name: "start-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec SearchHost.exe"
        on_right: "toggle_label"
